version: "3.7"

volumes:
  postgres_data:
  minio_data:
  grafana_data:

services:
  postgres:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./sql/init.sh:/docker-entrypoint-initdb.d/init.sh
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --replica-read-only no
    restart: always
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data
  auth:
    image: vor0lga/myaidkitauth:latest
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    restart: always
    links:
      - postgres:postgres
      - redis:redis
    depends_on:
      - postgres
      - redis
    ports:
      - "5555:5555"
  profile:
    image: vor0lga/myaidkitprofile:latest
    build:
      context: .
      dockerfile: ./cmd/profile/Dockerfile
    restart: always
    links:
      - postgres:postgres
      - minio:minio
    depends_on:
      - postgres
      - minio
    ports:
      - "6666:6666"
  main:
    image: vor0lga/myaidkitmain:latest
    build:
      context: .
      dockerfile: ./cmd/main/Dockerfile
    restart: always
    links:
      - postgres:postgres
      - redis:redis
      - minio:minio
      - auth:auth
      - profile:profile
    depends_on:
      - postgres
      - redis
      - minio
      - auth
      - profile
    ports:
      - "1323:1323"
  cron:
    image: vor0lga/myaidkitcron:latest
    build:
      context: .
      dockerfile: ./cmd/cron/Dockerfile
    restart: always
    links:
      - postgres:postgres
    depends_on:
      - postgres
    ports:
      - "9999:9999"
  nginx:
    image: nginx:latest
    links:
      - main:main
      - minio:minio
    restart: always
    depends_on:
      - minio
      - main
    volumes:
      - /home/ubuntu/myaidkit.ru.crt:/etc/ssl/myaidkit.ru.crt
      - /home/ubuntu/myaidkit.ru.key:/etc/ssl/myaidkit.ru.key  
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"


